{
    "buildkite_job_id": "018f422b-90c2-4932-b375-090c14fae232",
    "buildkite_url": "https://buildkite.com/ray-project/release/builds/14871#018f422b-90c2-4932-b375-090c14fae232",
    "cluster_id": "ses_38py2kh8tau1qqthhjv1ijtvr2",
    "cluster_url": "https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_38py2kh8tau1qqthhjv1ijtvr2",
    "extra_tags": {
        "buildkite_job_id": "018f422b-90c2-4932-b375-090c14fae232",
        "buildkite_pipeline_slug": "release",
        "buildkite_pull_request": "false",
        "buildkite_source": "trigger_job",
        "release_frequency": "nightly",
        "test_name": "stress_test_dead_actors.aws",
        "test_smoke_test": "False"
    },
    "job_id": "prodjob_hmhemqu69zezqclphyk3tnba3y",
    "job_url": "https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_hmhemqu69zezqclphyk3tnba3y",
    "last_logs": "2024-05-03 23:14:01,302\tERROR node_head.py:386 -- Cannot reach the node, fbb44e46a8bc2b4ade0cd733299267a6bbab57d1bfe2738347024ac0. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,303\tERROR node_head.py:386 -- Cannot reach the node, bf9cddcad80b3675a1116ca57648603c0616c6aadb6a7220661e3bfb. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,303\tERROR node_head.py:386 -- Cannot reach the node, 3470940addefdde1981c5179c8bb1807ac91ab8926dcc8dd9d933736. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,303\tERROR node_head.py:386 -- Cannot reach the node, e6bdad16b16ac5f9ae43bd59642d99d6c48405f0b00ba6a1277e2670. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,303\tERROR node_head.py:386 -- Cannot reach the node, 5958397db1ae7346d50d1dc139455a9f562630783717a9a6d13ec8ca. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,303\tERROR node_head.py:386 -- Cannot reach the node, b838a0d060426961d1acbdc44ee3ed3af2083a0a201ff4097e708141. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,303\tERROR node_head.py:386 -- Cannot reach the node, f8f85faeea5ca52e1955f4d7eb138d0ebe472880bb53fcf6f834477b. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,303\tERROR node_head.py:386 -- Cannot reach the node, 3e9d28850c243a4b72cd9a170870737ece5f29bdc8d5b4be09d0cab4. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,303\tERROR node_head.py:386 -- Cannot reach the node, 41d12c4215b5f67315a170f456891187e538050f6998121c0b6da1b8. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,304\tERROR node_head.py:386 -- Cannot reach the node, 25d4ebed2335f6e6fc08a9ce1e83941203cb58ef4f6f74080c51947a. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,304\tERROR node_head.py:386 -- Cannot reach the node, 6e052c5cfe32fea774befc69530421c8ce5c177783f6c5aeeedf1113. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,304\tERROR node_head.py:386 -- Cannot reach the node, c68cb95bd92220b4a6c1fa6a57166f363b3284eb5446b5afbc444444. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,304\tERROR node_head.py:386 -- Cannot reach the node, 08d609fa14649e2903b292a549592bd56a10d2eb3dbd34f970e2b55f. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,304\tERROR node_head.py:386 -- Cannot reach the node, 2309924348df810063ea2291eee40769d982c0b875b3a0387908aa3b. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,304\tERROR node_head.py:386 -- Cannot reach the node, 2e4597d92b8542734f6c8003583bd5390f249b47f97bfa0e661dea9b. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,304\tERROR node_head.py:386 -- Cannot reach the node, 95c4abbb6dc04ccbc38d50a22457a247412d6e200a163c93fabefee8. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,304\tERROR node_head.py:386 -- Cannot reach the node, 77a0a99537f8d58c541c06745184407a3320febea1a913a7c1c01c8f. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,305\tERROR node_head.py:386 -- Cannot reach the node, 32f72b9c6c33bbb92034d3560045c41def09563bd57e8adffb0560e5. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,305\tERROR node_head.py:386 -- Cannot reach the node, 9104c902c213cb916294c919e4654af95558bb94c40d1dc378cab044. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,305\tERROR node_head.py:386 -- Cannot reach the node, 9454b945211c4dda459d9373fa6d4a9557d7bc341bdb221337228373. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,305\tERROR node_head.py:386 -- Cannot reach the node, cfb817faaf5b4ea2653ed8cc207c8cdcc453b554f15c5d34ccd7d713. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,305\tERROR node_head.py:386 -- Cannot reach the node, 8bb234b06474bb8c1721fa516ce7ad9f099aa6b7d6b4df422a126ecd. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,305\tERROR node_head.py:386 -- Cannot reach the node, 2161c64e7b833baf79cc729326a8cdfcbd52e219e944244ac3f0f5c3. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,305\tERROR node_head.py:386 -- Cannot reach the node, 7a2ec59ac08a0912c5c9d401d6d9a92480990216b460147ea217cf14. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,305\tERROR node_head.py:386 -- Cannot reach the node, 10a6343c3547f51780757c08acee01c9621724c97a164e1e3b7e0a17. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,306\tERROR node_head.py:386 -- Cannot reach the node, 1f7a5e27ab89ad0252e3b02f01ce8f8886616fcf16dd893f44593f59. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,306\tERROR node_head.py:386 -- Cannot reach the node, 059e9754c4165c9e3325af8dc070258507f1e14ba114788f2d7cda96. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,306\tERROR node_head.py:386 -- Cannot reach the node, 60a4a37e7c61b103026beb23bbf7bbceda3681c4b07d882eba72cf02. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,306\tERROR node_head.py:386 -- Cannot reach the node, bb5be441d4b1065e9ebe0e599e00ef715d3bc9cd11e0e0df43be11f7. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,306\tERROR node_head.py:386 -- Cannot reach the node, 2f380bf5a0d3c2a26b68364b44932f038b6e3c0955822bedc2b7ac69. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,306\tERROR node_head.py:386 -- Cannot reach the node, b59c5b21ba3b2411c758a39f6dc7f30086824ebed1570ac8f6586bd3. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,306\tERROR node_head.py:386 -- Cannot reach the node, 0481a5bf94ae6626999ca33d8116719344327f1128f937dbfbf0d130. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,306\tERROR node_head.py:386 -- Cannot reach the node, f5002936e1b72b1db478a32d9e9ff27c3f4132d05d109f8afc130677. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,306\tERROR node_head.py:386 -- Cannot reach the node, 4ecf0e40dc205960cbb9ca030243712018bb15d3a614c6e9d3b2d375. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,307\tERROR node_head.py:386 -- Cannot reach the node, 915773e912c9d06e9d544e3b67d3277d01a32c972f46fb7aa7407eea. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,307\tERROR node_head.py:386 -- Cannot reach the node, 4adcfea18876b63348865ff08c408e385e8afca7383bd77fcc266210. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,307\tERROR node_head.py:386 -- Cannot reach the node, 31d9cee0feab216dd6a6286491d12bcd20e0d4c27ad563b2b4b9ab26. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,307\tERROR node_head.py:386 -- Cannot reach the node, 6b6bde71abf423f75795bd9ff8b98e0ed085d26354c2989d4b257511. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,307\tERROR node_head.py:386 -- Cannot reach the node, bee6a691ece212f070abe35b317c7caac65d7ef8b691e808bbc1fea2. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,307\tERROR node_head.py:386 -- Cannot reach the node, f4e0429e16ece7944d36ed243dea50f8caa116c53cb6c07d30feeb59. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,307\tERROR node_head.py:386 -- Cannot reach the node, 54d6a58441082ffda0d5abfbb814c25bbd98298fc5e5455b5f116e4f. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,308\tERROR node_head.py:386 -- Cannot reach the node, caa0b3f2f7225ca9e6e943059c168d426cb1a5b0d3fbc9ed998e75fd. The node may have been terminated.\nNoneType: None\n2024-05-03 23:14:01,838\tINFO web_log.py:206 -- 127.0.0.1 [04/May/2024:06:14:01 +0000] 'GET /api/component_activities?timeout=60 HTTP/1.1' 200 279 bytes 2667 us '-' 'Go-http-client/1.1'\n2024-05-03 23:14:01,839\tINFO web_log.py:206 -- 127.0.0.1 [04/May/2024:06:14:01 +0000] 'GET / HTTP/1.1' 200 259 bytes 2433 us '-' 'Go-http-client/1.1'\n2024-05-03 23:14:01,946\tINFO web_log.py:206 -- 127.0.0.1 [04/May/2024:06:14:01 +0000] 'GET /api/jobs/ HTTP/1.1' 200 3117 bytes 5272 us '-' 'Go-http-client/1.1'\n2024-05-03 23:14:02,952\tINFO web_log.py:206 -- 127.0.0.1 [04/May/2024:06:14:02 +0000] 'GET /api/jobs/ HTTP/1.1' 200 3117 bytes 5486 us '-' 'Go-http-client/1.1'\n2024-05-03 23:14:03,966\tINFO web_log.py:206 -- 127.0.0.1 [04/May/2024:06:14:03 +0000] 'GET /api/jobs/ HTTP/1.1' 200 3117 bytes 11389 us '-' 'Go-http-client/1.1'\n2024-05-03 23:14:04,026\tWARNING dashboard.py:236 -- Exiting with SIGTERM immediately...\n",
    "results": {
        "avg_iteration_time": 1.4795736622810365,
        "max_iteration_time": 5.597578763961792,
        "min_iteration_time": 0.6834812164306641,
        "perf_metrics": [
            {
                "perf_metric_name": "avg_iteration_time",
                "perf_metric_type": "LATENCY",
                "perf_metric_value": 1.4795736622810365
            }
        ],
        "success": 1,
        "total_time": 147.95764255523682
    },
    "return_code": 0,
    "runtime": 685.558357032,
    "smoke_test": false,
    "stable": true,
    "status": "success",
    "wheels_url": null
}
